In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv('/Volumes/Extreme SSD/Python_Projects/NIAA Project/data/data_in_one_row_without_spouses.csv')

In [6]:
df.head()

,nama orang,geb/overl.,organ.,werkgebied en -soort,werkperiode,bijzonderheden,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,id
0,"Aa, zr. W. van der (N)",1908-1942/5,GZB,"Rantepao (Sulsel), verpleegster",1932-1933,"~ 1933 F.R.O. Steller, contr. BB, z.v. hp E.T....",NaN,NaN,NaN,† in Japanse internering?,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,"Aalbers, dr. Joh. Godefr., arts (N)",1910-1992,NZG,Deli,1937-1946,1942-45 Japanse internering,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,"Aalders, zr. Jacoba (N)",1910-1999,SZ,"Bojonegoro, verpleegster in Zzh",1939-1942/6,> dir. Centraal Zh in Hollan­dia (Dake 64) > S...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3,"Abeel, David (VS)",1804-1846,ABCFM,"Batavia, bij Medhurst",1831,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
4,"Abkoude, ds. F.N.M. van (N)",1895-1988,mandiri,"pred. gem. Temanggung, MJava",1925-1942,EndSumba 839,NaN,NaN,ZGKN-S,"> pred. GKN, miss. pred. Sumba",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4

In [7]:
# Create a new dataframe with the first two columns and the last column
df1 = df.iloc[:, [0, 1, -1]]

In [8]:
# Write to csv
df1.to_csv('/Volumes/Extreme SSD/Python_Projects/NIAA Project/FINAL_PARSED_DATA/bio_data.csv', index=False)